### ISSUE TITLE
Speed issues

### ISSUE THREAD

**Issue by grigs** [ike/The-Future-Img-Tag#1]
Load time on a lower end phone is far too slow. It will take a very kind soul to wait through the full page load to see the results. Lots of script loading going on.

I’m going to open separate tickets with recommendations, but most of those recommendations are derived from this issue of download time on older devices which are the ones we need to test the most.

**Comment by ike** [comment]
The front page is super fast now... the main bandwidth-hogger was the Gist embed script. I inlined the CSS and HTML that was being downloaded by the script, and noticed a 15% increase in page load speed.
