### ISSUE TITLE
Move results iframe to separate html page

### ISSUE THREAD

**Issue by grigs** [ike/The-Future-Img-Tag#2]
Instead of burdening the test page with the results iframe, move it to a separate html document and link to it. This will reduce the download time substantially.

**Comment by ike** [comment]
Perfect! Not only that, but removing the MobileOptimized meta tags would make the iframe fill the screen on most devices, resulting in a better viewing experience.

**Comment by ike** [comment]
OK, this is fixed in the latest commit. Moved the results page to it's own thing.
