### ISSUE TITLE
Remove javascript dependency

### ISSUE THREAD

**Issue by grigs** [ike/The-Future-Img-Tag#4]
This one doesn't have a straightforward answer I’m afraid, but the ability to collect results from devices without javascript is a big deal. Might make sense to check with Lindsey Simon who is the lead on Browserscope to see if that is possible or if removing javascript from the picture takes it out of Browserscope’s scope (sorry).

**Comment by ike** [comment]
I need to look into using Node.js to user Browserscope's API from a server. That could work nicely for really old legacy phones, etc., that don't have JS support.
